language: ruby

rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - ruby-head
  - jruby-head
  - truffleruby

sudo: false

addons:
  apt:
    packages:
    - libgmp3-dev

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head

install:
  - bundle install

script: bundle exec rake

notifications:
  disable: true
