sudo: false
language: ruby
cache: bundler
rvm: 2.4

before_install:
  - gem update --system
install: bundle install
script: bundle exec jekyll build --trace

branches:
  only:
  - gh-pages

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
