# Build settings
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://liquidmarkup.org" # the base hostname & protocol for your site
markdown: kramdown
highlighter: pygments
permalink: /:year/:month/:day/:basename:output_ext
collections:
  docs:
    output: true
    permalink: /docs/:path/
exclude:
  - README.md
  - CNAME
  - node_modules
keep_files: ['css']
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  - scope:
      path: "docs/basics"
    values:
      type: "basics"
  - scope:
      path: "docs/filters"
    values:
      type: "filters"
  - scope:
      path: "docs/tags"
    values:
      type: "tags"
