# Build settings
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://liquidmarkup.org" # the base hostname & protocol for your site
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:basename:output_ext
collections:
  basics:
    output: true
    permalink: /basics/:path/
  filters:
    output: true
  tags:
    output: true
exclude:
  - README.md
  - CNAME
  - node_modules
keep_files: ['css']
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
