title: Liquid Templating Engine
description: "Liquid is a template language and accompanying rendering engine. It is built for security, so is perfect for rendering custom templates from your users."

# Build settings
baseurl:                "" # the subpath of your site, e.g. /blog/
url:                    http://liquidmarkup.org # the base hostname & protocol for your site
markdown:               kramdown
highlighter:            pygments
permalink:              /:year/:month/:day/:basename:output_ext
exclude:
  - README.md
  - CNAME
  - node_modules
keep_files:             ['css']

# Front matter defaults
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  - scope:
      path: "basics"
    values:
      type: "basics"
  - scope:
      path: "filters"
    values:
      type: "filters"
  - scope:
      path: "tags"
    values:
      type: "tags"
